name: todo
description: "🛠 Offers a TODO() method to indicate that code has not been implemented yet."
version: 2.0.0-nullsafety.0
homepage: https://github.com/marcelgarus/todo

environment:
  sdk: ">=2.12.0-0 <3.0.0"
